operator:
  replicas: 1
  affinity: {}
cluster:
  name: c0
  id: 0
ipam:
  operator:
    clusterPoolIPv4MaskSize: 24
    clusterPoolIPv4PodCIDRList:
    - 10.0.0.0/17
encryption:
  enabled: true
  type: wireguard
hubble:
  enabled: true
  relay:
    enabled: true
#  ui:
#    enabled: true
#  peerService:
#    clusterDomain: cluster.local
#  tls:
#    auto:
#      enabled: true
#      method: certmanager
#      certValidityDuration: 32
#      certManagerIssuerRef:
#        group: cert-manager.io
#        kind: Issuer
#        name: ca-issuer
