---
# htaccess file with demo credentials
apiVersion: v1
kind: Secret
metadata:
  name: htaccess
data:
  ht: Z2xhc3M6JGFwcjEkanZMTUhtREQkSmJUMzU0NEdpWHVXU2UwSVRCbXRBMQoK
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: basicauth
spec:
  basicAuth:
    secret: htaccess
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: basicauthremove
spec:
  basicAuth:
    removeHeader: true
    secret: htaccess
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: hubble-ui
spec:
  entryPoints:
  - http
  routes:
  - match: HostRegexp(`hubble.{domain:.+}`)
    kind: Rule
    middlewares:
    - name: basicauth
    services:
    - name: hubble-ui
      port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: hubble-relay
spec:
  entryPoints:
  - https
  tls: {}
  routes:
  - match: HostRegexp(`hubble-relay.{domain:.+}`)
    kind: Rule
    middlewares:
    - name: basicauth
    services:
    - name: hubble-relay
      port: 80
