kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kad-data
  namespace: kad
spec:
  accessModes:
  # aws ebs
  - ReadWriteOnce

  # rbd
  #- ReadWriteOnce

  # cephfs
  #- ReadWriteMany
  resources:
    requests:
      storage: 1Gi
